source "https://supermarket.chef.io"



metadata

cookbook 'snappydata', path: '../../cookbooks/snappydata'
cookbook 'snappydata-ycsb', path: '../../cookbooks/snappydata-ycsb'
cookbook 'apt-upgrade-once', '~> 0.2.1'
cookbook 'apt', '~> 3.0.0'
cookbook 'hostsfile'
