kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-worker-controller
spec:
  replicas: 2
  selector:
    component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: k8s4spark/spark:test
          command: ["/start-worker"]
          ports:
            - containerPort: 8081
            - containerPort: 7077
          resources:
            requests:
              cpu: 100m

