apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: spark-master
spec:
  serviceName: "spark-master"
  replicas: 1
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: k8s4spark/spark:test
          command:
            - "/bin/bash"
            - "-ecx"
            - |
              exec /bin/bash -c "cat /etc/passwd > /tmp/passwd && echo "$(id -u):x:$(id -u):$(id -g):dynamic uid:$SPARK_HOME:/bin/false" >> /tmp/passwd && export NSS_WRAPPER_PASSWD=/tmp/passwd && export LD_PRELOAD=libnss_wrapper.so && $SPARK_HOME/bin/spark-class org.apache.spark.deploy.master.Master --host $(hostname -f) --conf spark.snappydata.store.locators=snappydata-locator-0.snappydata-locator.snappydata.svc.cluster.local:10334,snappydata-locator-1.snappydata-locator.snappydata.svc.cluster.local:10334 --packages \"SnappyDataInc:snappydata:0.7-s_2.11\""
          ports:          
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
