apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: snappydata-locator
spec:
  serviceName: "snappydata-locator"
  replicas: 2 # Set to two on a cloud cluster
  template:
    metadata:
      labels:
        app: snappydata-locator
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
            {
                "name": "snappydata-locator-init",
                "image": "busybox",
                "imagePullPolicy": "IfNotPresent",
                "command": ["sh", "-c", "mkdir -p /snappydata/locator && chmod 777 /snappydata/locator"],
                "volumeMounts": [
                    {
                      "name": "datadir",
                      "mountPath": "/snappydata"
                    }
                ]
            }
        ]'
    spec:
      containers:
      - name: snappydata-locator
        # Runs the current snappydata release
        image: ifire/snappydata:0.8p1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "2048Mi"
            cpu: "100m"
        ports:
        - containerPort: 10334
          name: locator
        - containerPort: 1527
          name: snappydata
        - containerPort: 7075
          name: pulse
        livenessProbe:
          tcpSocket:
            port: 10334
          initialDelaySeconds: 80
        readinessProbe:
          tcpSocket:
            port: 10334
          initialDelaySeconds: 80
        volumeMounts:
        - name: datadir
          mountPath: /snappydata
        command:
          - "/bin/bash"
          - "-ecx"
          - |
            exec /bin/bash -c "export USER_ID=$(id -u) && export GROUP_ID=$(id -g) && envsubst < /opt/snappydata/passwd > /tmp/passwd && export LD_PRELOAD=/usr/lib64/libnss_wrapper.so && export NSS_WRAPPER_PASSWD=/tmp/passwd && export NSS_WRAPPER_GROUP=/etc/group && /opt/snappydata/bin/snappy locator start -dir=/snappydata/locator -thrift-server-address=$(hostname -f) -thrift-server-port=1530 -thrift-binary-protocol=true -locators=snappydata-locator-0.snappydata-locator.$MY_POD_NAMESPACE.svc.cluster.local:10334 -peer-discovery-address=$(hostname -f) -membership-port-range=21000-21020 -client-bind-address=$(hostname -f)  -thrift-binary-protocol=true -thrift-framed-transport=true -enable-network-partition-detection=true -jmx-manager=true -jmx-manager-http-port=7075 -jmx-manager-start=true && tail -f /snappydata/locator/snappylocator.log"
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        lifecycle:
          preStop:
            exec:
              command:
              - /opt/snappydata/bin/snappy locator stop -dir=/snappydata/locator
      terminationGracePeriodSeconds: 300
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: datadir
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 5Gi
