- hosts: all
  vars:
  tasks:
    - name: upgrade all packages
      apk: upgrade=yes
    - name: install openjdk 1.8
      apk: name=openjdk8-jre state=latest
    - name: install bash
      apk: name=bash state=latest
    - name: install busybox-suid
      apk: name=busybox-suid state=latest 
    - name: install shadow package
      shell: apk add 'shadow' --update-cache --repository https://nl.alpinelinux.org/alpine/edge/community
    - name: remove root password
      shell: passwd -d root
    - name: create snappydata directory
      file: path=/opt/snappydata state=directory
    - name: create snappydata user
      user: name=snappydata uid=1234321 group=root comment="SnappyData" home=/opt/snappydata shell=/bin/bash system=true
    - name: change snappydata directory ownership
      file: path=/opt/snappydata state=directory owner=snappydata group=root
    - name: install tar package
      apk: name=tar state=latest
    - name: download snappydata
      get_url:
        url: https://github.com/SnappyDataInc/snappydata/releases/download/v0.7/snappydata-0.7-bin.tar.gz
        dest: /tmp/snappydata.tar.gz
        mode: 0440  
      become: yes
      become_user: snappydata  
    - name: extract snappydata
      shell: tar -xvf /tmp/snappydata.tar.gz --strip 1 -C /opt/snappydata
      become: yes
      become_user: snappydata
    - name: delete archive
      file: 
        path: /tmp/snappydata.tar.gz
        state: absent
    - name: copy snappydata start config
      template: src=templates/start dest=/usr/local/bin/start mode=755
    - name: help uid fix
      file:
        path: /etc/passwd
        mode: 664
    - name: help uid fix
      file:
        path: /etc/group
        mode: 664    
  handlers:
