apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: gocd-agent-fedora-30
spec:
  selector:
    matchLabels:
      app: gocd-agent-fedora-30 # has to match .spec.template.metadata.labels
  updateStrategy:
    type: RollingUpdate
  serviceName: "gocd-agent-fedora-29"
  replicas: 3
  template:
    metadata:
      labels:
        app: gocd-agent-fedora-30 # has to match .spec.selector.matchLabels
    spec:
      tolerations:
      - key: "gke-preemptible"
        operator: "Exists"
      initContainers:
      - name: copy-ssh
        image: busybox
        command: ['/bin/sh', '-c', 'rm -rf /home/go/.ssh/ && cp -rf /root/gocd_ssh /home/go/.ssh/ && chown -R 1000:1000 /home/go/.ssh/']
        volumeMounts:
        - name: gohome
          mountPath: /home/go
        - name: gocd-agent-secret
          mountPath: /root/gocd_ssh/
      containers:
      - name: gocd-agent-fedora-30
        image: ifire/gocd-agent-fedora-30:v19.5.0-chibifire-0.2
        resources:
          requests:
            cpu: 800m
            memory: 1.8G
          limits:
            cpu: 1800m
        ports:
        env:
        - name: GO_SERVER_URL
          value: "https://gocd-server:8154/go"
        volumeMounts:
        - name: godata
          mountPath: /godata
        - name: gohome
          mountPath: /home/go
      volumes:
      - name: gocd-agent-secret
        secret:
          secretName: gocd-agent-secret
          defaultMode: 0400
  volumeClaimTemplates:
  - metadata:
      name: godata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 80Gi
  - metadata:
      name: gohome
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
