apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zeppelin
spec:
  serviceName: "zeppelin"
  replicas: 1
  template:
    metadata:
      labels:
        app: zeppelin
    spec:
      containers:
        - name: zeppelin
          env:
          - name: ZEPPELIN_PORT
            value: "8080"
          image: ifire/zeppelin:0.7.2
          command:
          - "/bin/bash"
          - "-ecx"
          - |
            mkdir -p /opt/zeppelin/interpreter/snappydata/ && curl -o /opt/zeppelin/interpreter/snappydata/snappydata-zeppelin-0.7.1.jar -L https://github.com/SnappyDataInc/zeppelin-interpreter/releases/download/v0.7.1/snappydata-zeppelin-0.7.1.jar && export USER_ID=$(id -u) && export GROUP_ID=$(id -g) && envsubst < /opt/zeppelin/passwd > /tmp/passwd && export LD_PRELOAD=/usr/lib64/libnss_wrapper.so && export NSS_WRAPPER_PASSWD=/tmp/passwd && export NSS_WRAPPER_GROUP=/etc/group && /opt/zeppelin/bin/zeppelin.sh
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
          volumeMounts:
          - name: logdir
            mountPath: /opt/zeppelin/logs/
          - name: rundir
            mountPath: /opt/zeppelin/run/
  volumeClaimTemplates:
  - metadata:
      name: logdir
      annotations:
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: rundir
      annotations:
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
