- name: create zeppelin directory
  file: path=/opt/zeppelin state=directory
- name: create snappydata user
  user: name=zeppelin group=root comment="Zeppelin" home=/opt/zeppelin shell=/bin/bash system=true
- name: copy snappydata passwd config
  template: src=templates/passwd.template dest=/opt/zeppelin/passwd mode=755    
- name: change snappydata directory ownership
  file: path=/opt/zeppelin state=directory owner=zeppelin group=root
- name: download zeppelin
  get_url:
    url: http://apache.mirror.iweb.ca/zeppelin/zeppelin-0.7.3/zeppelin-0.7.3-bin-all.tgz
    dest: /tmp/zeppelin.tar.gz
    mode: 0440  
  become: yes
  become_user: zeppelin    
- name: extract snappydata
  shell: tar -xvf /tmp/zeppelin.tar.gz --strip 1 -C /opt/zeppelin
  become: yes
  become_user: zeppelin
- name: delete archive
  file: 
    path: /tmp/zeppelin.tar.gz
    state: absent
- name: create snappydata directory
  file: path=/opt/zeppelin/interpreter/snappydata state=directory
- name: change snappydata directory ownership
  file: path=/opt/zeppelin/interpreter/snappydata state=directory owner=zeppelin group=root
- name: download snappydata interpreter
  get_url:
    url: https://github.com/fire/zeppelin-interpreter/releases/download/v0.7.3-rc0/snappydata-zeppelin-0.7.3-all.jar
    dest: /opt/zeppelin/interpreter/snappydata/snappydata-zeppelin-0.7.3-all.jar
    mode: 0440  
  become: yes
  become_user: zeppelin
