apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: snappydata-leader
spec:
  serviceName: "snappydata-leader"
  replicas: 1
  template:
    metadata:
      labels:
        app: snappydata-leader
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
            {
                "name": "snappydata-leader-init",
                "image": "busybox",
                "imagePullPolicy": "IfNotPresent",
                "command": ["sh", "-c", "mkdir -p /snappydata/leader && chmod 777 /snappydata/leader"],
                "volumeMounts": [
                    {
                      "name": "datadir",
                      "mountPath": "/snappydata"
                    }
                ]
            },
            {
                "name": "snappydata-wait-server",
                "image": "busybox",
                "imagePullPolicy": "IfNotPresent",
                "command": ["sh", "-c", "nslookup snappydata-server"]
            }
        ]'
    spec:
      containers:
      - name: snappydata-leader
        # Runs the current snappydata release
        image: ifire/snappydata:0.9
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "2048Mi"
            cpu: "100m"
        ports:
        - containerPort: 5050
          name: http
        - containerPort: 10334
          name: locator
        - containerPort: 3768
          name: zeppelin
        - containerPort: 21000
          name: membership-0000
        - containerPort: 21001
          name: membership-0001
        - containerPort: 21002
          name: membership-0002
        - containerPort: 21003
          name: membership-0003
        - containerPort: 21004
          name: membership-0004
        - containerPort: 21005
          name: membership-0005
        - containerPort: 21006
          name: membership-0006
        - containerPort: 21007
          name: membership-0007
        - containerPort: 21008
          name: membership-0008
        - containerPort: 21009
          name: membership-0009
        - containerPort: 21010
          name: membership-0010
        - containerPort: 21011
          name: membership-0011
        - containerPort: 21012
          name: membership-0012
        - containerPort: 21013
          name: membership-0013
        - containerPort: 21014
          name: membership-0014
        - containerPort: 21015
          name: membership-0015
        - containerPort: 21016
          name: membership-0016
        - containerPort: 21017
          name: membership-0017
        - containerPort: 21018
          name: membership-0018
        - containerPort: 21019
          name: membership-0019
        - containerPort: 21020
          name: membership-0020
        volumeMounts:
        - name: datadir
          mountPath: /snappydata
        command:
          - "/bin/bash"
          - "-ecx"
          - |
            exec /bin/bash -c "export USER_ID=$(id -u) && export GROUP_ID=$(id -g) && envsubst < /opt/snappydata/passwd > /tmp/passwd && export LD_PRELOAD=/usr/lib64/libnss_wrapper.so && export NSS_WRAPPER_PASSWD=/tmp/passwd && export NSS_WRAPPER_GROUP=/etc/group && /opt/snappydata/bin/snappy leader start -dir=/snappydata/leader -zeppelin.interpreter.enable=true -locators=snappydata-locator-0.snappydata-locator.$MY_POD_NAMESPACE.svc.cluster.local:10334,snappydata-locator-1.snappydata-locator.$MY_POD_NAMESPACE.svc.cluster.local:10334 -client-bind-address=$(hostname -f) -heap-size=4096m -membership-port-range=21000-21020 -J-XX:MaxPermSize=512m -enable-network-partition-detection=true && tail -f /snappydata/leader/snappyleader.log"
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        lifecycle:  
          preStop: 
            exec:
              command:
              - /opt/snappydata/bin/snappy leader stop -dir=/snappydata/leader
      terminationGracePeriodSeconds: 300
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: datadir
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 5Gi
