apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: snappydata-server
spec:
  serviceName: "snappydata-server"
  replicas: 1
  template:
    metadata:
      labels:
        app: snappydata-server
      annotations:
    spec:
      initContainers:
      - name: snappydata-server-init
        image: busybox
        command: ["sh", "-c", "mkdir -p /snappydata/server && chmod 777 /snappydata/server"]
        volumeMounts:
      containers:
      - name: snappydata-server
        # Runs the current snappydata release
        image: ifire/snappydata:0.9p1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "4096Mi"
            cpu: "100m"
        ports:
        - containerPort: 10334
          name: locator
        - containerPort: 1527
          name: snappydata
        - containerPort: 21000
          name: membership-0000
        - containerPort: 21001
          name: membership-0001
        - containerPort: 21002
          name: membership-0002
        - containerPort: 21003
          name: membership-0003
        - containerPort: 21004
          name: membership-0004
        - containerPort: 21005
          name: membership-0005
        - containerPort: 21006
          name: membership-0006
        - containerPort: 21007
          name: membership-0007
        - containerPort: 21008
          name: membership-0008
        - containerPort: 21009
          name: membership-0009
        - containerPort: 21010
          name: membership-0010
        - containerPort: 21011
          name: membership-0011
        - containerPort: 21012
          name: membership-0012
        - containerPort: 21013
          name: membership-0013
        - containerPort: 21014
          name: membership-0014
        - containerPort: 21015
          name: membership-0015
        - containerPort: 21016
          name: membership-0016
        - containerPort: 21017
          name: membership-0017
        - containerPort: 21018
          name: membership-0018
        - containerPort: 21019
          name: membership-0019
        - containerPort: 21020
          name: membership-0020
        livenessProbe:
          tcpSocket:
            port: 1527
          initialDelaySeconds: 180
        volumeMounts:
        - name: datadir
          mountPath: /snappydata
        - name: tlsdir
          mountPath: /tls
        command:
          - "/bin/bash"
          - "-ecx"
          - |
            exec /bin/bash -c "rm -f /snappydata/truststore && keytool -importcert -noprompt -file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -keystore /snappydata/truststore -alias Kubernetes -storepass changeit && openssl pkcs12 -export -in /tls/tls.crt -inkey /tls/tls.key -out server.p12 -name tls -CAfile /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -caname kubernetes -password pass:changeit && rm -f /snappydata/keystore && keytool -importkeystore -srckeystore server.p12 -srcstoretype pkcs12 -destkeystore /snappydata/keystore -deststoretype JKS -srcstorepass changeit -deststorepass changeit && export USER_ID=$(id -u) && export GROUP_ID=$(id -g) && envsubst < /opt/snappydata/passwd > /tmp/passwd && export LD_PRELOAD=/usr/lib64/libnss_wrapper.so && export NSS_WRAPPER_PASSWD=/tmp/passwd && export NSS_WRAPPER_GROUP=/etc/group && cd /snappydata/server && java -server -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=50 -XX:+CMSClassUnloadingEnabled -XX:NewRatio=6 -XX:-DontCompileHugeMethods -XX:+UnlockDiagnosticVMOptions -XX:ParGCCardsPerStrideChunk=4k -Djava.awt.headless=true -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.Log4JLogger -classpath /opt/snappydata/conf/:/opt/snappydata/jars/* io.snappydata.tools.ServerLauncher server sys-disk-dir=/snappydata/server -bind-address=$(hostname -f) thrift-ssl=true thrift-ssl-properties=keystore=/snappydata/keystore,keystore-password=changeit,truststore=/snappydata/truststore,truststore-password=changeit locators=snappydata-locator-0.snappydata-locator.$MY_POD_NAMESPACE.svc.cluster.local:10334,snappydata-locator-1.snappydata-locator.$MY_POD_NAMESPACE.svc.cluster.local:10334 -client-bind-address=$(hostname -f) -J-Djava.net.preferIPv4Stack=true -heap-size=4096m thrift-binary-protocol=true thrift-framed-transport=true -membership-port-range=21000-21020 enable-network-partition-detection=true -sync=true"
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        lifecycle:
          preStop:
            exec:
              command:
              - /opt/snappydata/bin/snappy server stop -dir=/snappydata/server
#      terminationGracePeriodSeconds: 300
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: datadir
      - name: tlsdir
        secret:
          secretName: snappydata-server-tls
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 5Gi
