apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: gitlab
spec:
  replicas: 1
  serviceName: gitlab
  template:
    metadata:
      labels:
        name: gitlab
    spec:
      containers:
      - name: gitlab
        resources:
          requests:
            cpu: 600m
        image: sameersbn/gitlab:11.2.3
        env:
        - name: GITLAB_BACKUP_EXPIRY
          value: "259200"
        - name: GCS_BACKUPS
          value: "true"
        - name: GCS_BACKUP_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: GCS_BACKUP_ACCESS_KEY_ID
        - name: GCS_BACKUP_BUCKET
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: GCS_BACKUP_BUCKET
        - name: GCS_BACKUP_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: GCS_BACKUP_SECRET_ACCESS_KEY
        - name: GITLAB_HTTPS
          value: "true"
        - name: SSL_SELF_SIGNED
          value: "true"
        - name: GITLAB_EMAIL
          value: "noreply@chibifire.com"
        - name: TZ
          value: UTC
        - name: GITLAB_TIMEZONE
          value: America/Los_Angeles
        - name: GITLAB_SECRETS_DB_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: GITLAB_SECRETS_DB_KEY_BASE
        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: GITLAB_SECRETS_SECRET_KEY_BASE
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: GITLAB_SECRETS_OTP_KEY_BASE
        - name: GITLAB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: GITLAB_ROOT_PASSWORD
        - name: GITLAB_ROOT_EMAIL
          value: ernest.lee@chibifire.com
        - name: GITLAB_HOST
          value: spark.apps.chibifire.com
        - name: GITLAB_SSH_HOST
          value: git.chibifire.com
        - name: GITLAB_SSH_PORT
          value: "22"

        - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
          value: "true"
        - name: GITLAB_NOTIFY_PUSHER
          value: "false"

        - name: GITLAB_BACKUP_SCHEDULE
          value: daily
        - name: GITLAB_BACKUP_TIME
          value: 01:00

        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: postgresql
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: gitlab
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: DB_PASS
        - name: DB_NAME
          value: gitlab_production

        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"

        - name: SMTP_ENABLED
          value: "true"
        - name: SMTP_DOMAIN
          value: spark.apps.chibifire.com
        - name: SMTP_HOST
          value: smtp.sendgrid.net
        - name: SMTP_PORT
          value: "2525"
        - name: SMTP_USER
          value: apikey
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: SMTP_PASS
        - name: SMTP_STARTTLS
          value: "true"
        - name: SMTP_AUTHENTICATION
          value: login

        - name: IMAP_ENABLED
          value: "false"
        - name: IMAP_HOST
          value: imap.gmail.com
        - name: IMAP_PORT
          value: "993"
        - name: IMAP_USER
          value: mailer@example.com
        - name: IMAP_PASS
          value: password
        - name: IMAP_SSL
          value: "true"
        - name: IMAP_STARTTLS
          value: "false"
        
        - name: OAUTH_GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: OAUTH_GOOGLE_API_KEY
        - name: OAUTH_GOOGLE_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: OAUTH_GOOGLE_APP_SECRET

        - name: GITLAB_MATTERMOST_ENABLED
          value: "true"
        - name: GITLAB_MATTERMOST_URL
          value: "https://mattermost.apps.chibifire.com"
        ports:
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22
        volumeMounts:
        - mountPath: /home/git/data
          name: data
        # livenessProbe:
        #   httpGet:
        #     path: /help
        #     port: 80
        #   initialDelaySeconds: 360
        #   timeoutSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: /help
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 1
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 60Gi
