# Copyright 2017 ThoughtWorks, Inc.
# Copyright 2018 K. S. Ernest (iFire) Lee
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM gocd/gocd-agent-centos-7:v18.1.0
MAINTAINER GoCD <go-cd-dev@googlegroups.com>

RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh | bash
RUN yum install -y git-lfs
RUN git lfs install
RUN yum install -y epel-release scons
RUN yum upgrade -y
RUN yum install -y clang
RUN yum install -y mingw64-gcc-c++
RUN yum install -y python34-pip
RUN pip3 install -U setuptools
RUN pip3 install -U wheel
RUN pip3 install scons
RUN yum install -y mingw64-winpthreads
RUN yum install -y mingw64-winpthreads-static
RUN yum group install -y "Development Tools"
RUN yum install -y libX11-devel libXcursor-devel libXrandr-devel libXinerama-devel \
    libXi-devel mesa-libGL-devel alsa-lib-devel pulseaudio-libs-devel freetype-devel openssl-devel \
    libudev-devel mesa-libGLU-devel