apiVersion: v1
kind: Service
metadata:
  name: store-cockroachdb-public
  namespace: default
spec:
  ports:
  - name: grpc
    port: 26257
    protocol: TCP
    targetPort: 26257
  selector:
    component: store-cockroachdb
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}