# https://daemonza.github.io/2017/02/13/kubernetes-nginx-ingress-controller/
apiVersion: v1
data:
  proxy-connect-timeout: "15"
  proxy-read-timeout: "600"
  proxy-send-timeout: "600"
  hsts-include-subdomains: "false"
  body-size: "64m"
  server-name-hash-bucket-size: "256"
#  use-proxy-protocol: "true"
  enable-sticky-sessions: "true"
kind: ConfigMap
metadata:
  namespace: nginx-ingress
  name: nginx
