apiVersion: v1
kind: Service
metadata:
  # This service is meant to be used by clients of the database. It exposes the locator so that the
  # servers can find other servers.
  name: snappydata-locator-public
  namespace: snappydata
  labels:
    app: snappydata
spec:
  ports:
  - port: 1527
    targetPort: 1527
    name: jdbc
  - port: 10334
    targetPort: 10334
    name: locator
  selector:
    app: snappydata-locator
