apiVersion: v1
kind: Service
metadata:
  name: postgresql-tabletop-rpg-web
  labels:
    name: postgresql
spec:
  type: LoadBalancer
  selector: 
    name: postgresql-tabletop-rpg-web
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
