apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: snappydata-server
spec:
  updateStrategy: 
    type: "RollingUpdate"
  serviceName: "snappydata-server"
  replicas: 3
  template:
    metadata:
      labels:
        type: snappydata-server
        app: snappydata
    spec:
      initContainers:
      - name: "snappydata-server-init"
        image: "busybox"
        imagePullPolicy: "IfNotPresent"
        command: ["/bin/sh"]
        args: ["-c", "mkdir -p /snappydata/server && chmod 777 /snappydata/server"]
        volumeMounts:
        - mountPath: "/snappydata"
          name: "datadir"
      - name: "pem-to-keystore"
        image: "tomcat:8.0.50-jre7"
        env:
        - name: ca_bundle
          value: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        - name: "keyfile"
          value: "/var/run/secrets/openshift.io/services_serving_certs/tls.key"
        - name: "crtfile"
          value: "/var/run/secrets/openshift.io/services_serving_certs/tls.crt"
        - name: "keystore_pkcs12"
          value: "/var/run/secrets/java.io/keystores/keystore.pkcs12"
        - name: "keystore_jks"
          value: "/var/run/secrets/java.io/keystores/keystore.jks"
        - name: "password"
          value: "changeit"
        command: ['/bin/bash']
        args: ['-c', "openssl pkcs12 -export -inkey $keyfile -in $crtfile -out $keystore_pkcs12 -password pass:$password && mv $keystore_pkcs12 $keystore_jks"]
        volumeMounts:
          - mountPath: "/var/run/secrets/java.io/keystores"
            name: "keystore-volume"
          - mountPath: "/var/run/secrets/openshift.io/services_serving_certs"
            name: "service-certs"
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: datadir
      - name: keystore-volume
        emptyDir: {}
      - name: service-certs
        secret:
          secretName: service-certs
      containers:
      - name: snappydata-server
        image: ifire/snappydata-server:20180312020211
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "4096Mi"
            cpu: "100m"
        ports:
        - containerPort: 10334
          name: locator
        - containerPort: 1527
          name: snappydata
        - containerPort: 21000
          name: membership-0000
        - containerPort: 21001
          name: membership-0001
        - containerPort: 21002
          name: membership-0002
        - containerPort: 21003
          name: membership-0003
        - containerPort: 21004
          name: membership-0004
        - containerPort: 21005
          name: membership-0005
        - containerPort: 21006
          name: membership-0006
        - containerPort: 21007
          name: membership-0007
        - containerPort: 21008
          name: membership-0008
        - containerPort: 21009
          name: membership-0009
        - containerPort: 21010
          name: membership-0010
        - containerPort: 21011
          name: membership-0011
        - containerPort: 21012
          name: membership-0012
        - containerPort: 21013
          name: membership-0013
        - containerPort: 21014
          name: membership-0014
        - containerPort: 21015
          name: membership-0015
        - containerPort: 21016
          name: membership-0016
        - containerPort: 21017
          name: membership-0017
        - containerPort: 21018
          name: membership-0018
        - containerPort: 21019
          name: membership-0019
        - containerPort: 21020
          name: membership-0020
        livenessProbe:
          tcpSocket:
            port: 1527
          initialDelaySeconds: 180
        volumeMounts:
        - name: datadir
          mountPath: /snappydata
        - mountPath: "/var/run/secrets/java.io/keystores"
          name: "keystore-volume"
        command:
          - "/bin/bash"
          - "-ecx"
          - |
            exec /bin/bash -c "export USER_ID=$(id -u) && export GROUP_ID=$(id -g) && envsubst < /opt/snappydata/passwd > /tmp/passwd && export LD_PRELOAD=/usr/lib64/libnss_wrapper.so && export NSS_WRAPPER_PASSWD=/tmp/passwd && export NSS_WRAPPER_GROUP=/etc/group && cd /snappydata/server && java -server -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=50 -XX:+CMSClassUnloadingEnabled -XX:NewRatio=6 -XX:-DontCompileHugeMethods -XX:+UnlockDiagnosticVMOptions -XX:ParGCCardsPerStrideChunk=4k -Djava.awt.headless=true -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.Log4JLogger -classpath /opt/snappydata/conf/:/opt/snappydata/jars/* -Dalluxio.user.file.writetype.default=CACHE_THROUGH io.snappydata.tools.ServerLauncher server -bind-address=$(hostname -f) locators=snappydata-locator-0.snappydata-locator.$MY_POD_NAMESPACE.svc.cluster.local:10334,snappydata-locator-1.snappydata-locator.$MY_POD_NAMESPACE.svc.cluster.local:10334 -client-bind-address=$(hostname -f) -heap-size=4096m thrift-binary-protocol=true thrift-framed-transport=true -membership-port-range=21000-21020 enable-network-partition-detection=true thrift-ssl=true thrift-ssl-properties=keystore=/var/run/secrets/java.io/keystores/keystore.jks,keystore-password=changeit,protocol=TLS,enabled-protocols=TLSv1:TLSv1.1:TLSv1.2,cipher-suites=TLS_RSA_WITH_AES_128_CBC_SHA:TLS_RSA_WITH_AES_256_CBC_SHA:TLS_RSA_WITH_AES_128_CBC_SHA256:TLS_RSA_WITH_AES_256_CBC_SHA256,client-auth=false"
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 5Gi
