apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: monicahq-mariadb
  name: monicahq-mysql
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: monicahq-mariadb
status:
  loadBalancer: {}
