apiVersion: v1
kind: Service
metadata:
  # This service is meant to be used by clients of the database. It exposes a ClusterIP that will
  # automatically load balance connections to the different database pods.
  name: alluxio-master-public
  labels:
    app: alluxio
spec:
  ports:
  - name: "19999"
    port: 19999
    targetPort: 19999
  - name: "19998"
    port: 19998
    targetPort: 19998
  - name: "30000"
    port: 30000
    targetPort: 30000
  selector:
    type: alluxio-master
