version: "2"
services:
  monicahq:
    build: .
    image: monicahq/monicahq:v1.8.2
    links:
      - mariadb
    ports:
      - 80:80
    env_file: .env
    volumes:
      - ./persist/storage/app/public:/var/www/monica/storage/app/public

  mariadb:
    image: mariadb:10.3.5
    environment:
      - MYSQL_ROOT_PASSWORD=sekret_root_password
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    volumes:
      - ./persist/mysql:/var/lib/mysql
