apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx-ingress
  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "true"
    service.beta.kubernetes.io/external-traffic: "OnlyLocal"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
  - port: 2222
    name: ssh
  - port: 443
    name: https
  selector:
    app: nginx
