apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    name: gitlab
spec:
  clusterIP: None
  selector: 
    app: gitlab
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: ssh
      port: 2222
      targetPort: ssh
  selector:
    name: gitlab
