apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    name: postgresql
spec:
  clusterIP: None
  selector: 
    name: postgresql
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    name: postgresql
