apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: snappydata-locator
spec:
  updateStrategy: 
    type: "RollingUpdate"
  serviceName: "snappydata-locator"
  replicas: 3
  template:
    metadata:
      labels:
        type: snappydata-locator
        app: snappydata
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
            {
                "name": "snappydata-locator-init",
                "image": "busybox",
                "imagePullPolicy": "IfNotPresent",
                "command": ["sh", "-c", "mkdir -p /snappydata/locator && chmod 777 /snappydata/locator"],
                "volumeMounts": [
                    {
                      "name": "datadir",
                      "mountPath": "/snappydata"
                    }
                ]
            }
        ]'
    spec:
      containers:
      - name: snappydata-locator
        # Runs the current snappydata release
        image: ifire/snappydata-locator:20171118235048
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "1200Mi"
            cpu: "100m"
        ports:
        - containerPort: 10334
          name: locator
        - containerPort: 1527
          name: snappydata
        livenessProbe:
          tcpSocket:
            port: 10334
          initialDelaySeconds: 30
        readinessProbe:
          tcpSocket:
            port: 10334
          initialDelaySeconds: 30
        volumeMounts:
        - name: datadir
          mountPath: /snappydata
        command:
          - "/bin/bash"
          - "-ecx"
          - |
            exec /bin/bash -c "export USER_ID=$(id -u) && export GROUP_ID=$(id -g) && envsubst < /opt/snappydata/passwd > /tmp/passwd && export LD_PRELOAD=/usr/lib64/libnss_wrapper.so && export NSS_WRAPPER_PASSWD=/tmp/passwd && export NSS_WRAPPER_GROUP=/etc/group && cd /snappydata/locator && java -server -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=50 -XX:+CMSClassUnloadingEnabled -XX:NewRatio=6 -XX:-DontCompileHugeMethods -XX:+UnlockDiagnosticVMOptions -XX:ParGCCardsPerStrideChunk=4k -Djava.awt.headless=true -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.Log4JLogger -classpath /opt/snappydata/conf/:/opt/snappydata/jars/* io.snappydata.tools.LocatorLauncher server -thrift-server-address=$(hostname -f) -thrift-server-port=1530 -peer-discovery-address=$(hostname -f) -membership-port-range=21000-21020 -client-bind-address=$(hostname -f) locators=snappydata-locator-0.snappydata-locator.$MY_POD_NAMESPACE.svc.cluster.local:10334 thrift-binary-protocol=true thrift-framed-transport=true enable-network-partition-detection=true -jmx-manager=false -jmx-manager-http-port=7075 -jmx-manager-start=false -sync=true"
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: datadir
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 5Gi
