apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
spec:
  clusterIP: None
  selector: 
    name: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    name: redis
