apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: gocd-agent-fedora-28
spec:
  selector:
    matchLabels:
      app: gocd-agent-fedora-28 # has to match .spec.template.metadata.labels
  serviceName: "gocd-agent-fedora-28"
  replicas: 1
  template:
    metadata:
      labels:
        app: gocd-agent-fedora-28 # has to match .spec.selector.matchLabels
    spec:
      tolerations:
      - key: "gke-preemptible"
        operator: "Exists"
      containers:
      - name: gocd-agent-fedora-28
        image: ifire/gocd-agent-fedora-28:v18.9.0-chibifire-0.1
        resources:
          requests:
            cpu: 800m
          limits:
            cpu: 1800m
        ports:
        env:
        - name: GO_SERVER_URL
          value: "https://gocd-server:8154/go"
        volumeMounts:
        - name: godata
          mountPath: /godata
        - name: gohome
          mountPath: /home/go
  volumeClaimTemplates:
  - metadata:
      name: godata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: gohome
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
